- name: Retrieve SSL certificate expiration dates

  hosts: localhost

  gather_facts: false

  tasks:

    - name: Retrieve SSL certificate expiration date for each domain

      shell: "echo | openssl s_client -servername csl.com -connect csl.com:443 2>/dev/null | openssl x509 -noout -enddate"

      register: certificate_output




    - name: Extract certificate expiration dates

      set_fact:

        certificate_expiration_dates: "{{ certificate_output.results | map(attribute='stdout') | map('regex_replace', '^.*notAfter=(.*)$', '\\1') | list }}"



    - name: Display certificate expiration dates

      debug:

        msg: "The SSL certificate for {{ item.0 }} expires on {{ item.1 }}"

      with_together:

        - "{{ domain_names }}"

        - "{{ certificate_expiration_dates }}"
